# @format

# Simple workflow for deploying static content to GitHub Pages
name: Release to GitHub Pages

on:
    release:
        types: [created]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Build
              run: yarn build
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: |
                      ./dist
                      !./dist/*.map
            - name: Upload Source Maps
              uses: actions/upload-artifact@v3
              with:
                  name: sourcemaps
                  path: "./dist/*.map"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
            - name: Download Sourcemaps
              uses: actions/download-artifact@v3
              with:
                  name: sourcemaps
            - name: Notify deploy to Rollbar
              uses: rollbar/github-deploy-action@2.1.2
              id: rollbar_deploy
              with:
                  environment: "production"
                  version: ${{ github.sha }}
                  source_maps: sourcemaps
              env:
                  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
                  ROLLBAR_USERNAME: ${{ github.actor }}
